const IMAGES = {
    layer1 : new URL('./layer1-ocean.png',import.meta.url).href,
    layer2 : new URL('./layer2-tw_island.png',import.meta.url).href,
    layer3a : new URL('./layer3a-path3.png',import.meta.url).href,
    layer3b: new URL('./layer3b-path2.png',import.meta.url).href,
    layer3c: new URL('./layer3c-path1.png',import.meta.url).href,
    layer3d: new URL('./layer3d-path0.png',import.meta.url).href,
    layer4 : new URL('./layer4-forest_back.png',import.meta.url).href,
    layer4a: new URL('./layer4a-blockers2.png', import.meta.url).href,
    layer4b: new URL('./layer4b-blockers3.png', import.meta.url).href,
    layer5 : new URL('./layer5-station2.png',import.meta.url).href,
    layer6 : new URL('./layer6-tracks.png',import.meta.url).href,
    layer7 : new URL('./layer7-vendingmachine.png',import.meta.url).href,
    layer8 : new URL('./layer8-library.png',import.meta.url).href,
    train : new URL('./layer9-train.png',import.meta.url).href,
    layer10 : new URL('./layer10-forest_middle.png',import.meta.url).href,
    layer11 : new URL('./layer11-diner.png',import.meta.url).href,
    layer12 : new URL('./layer12-station1.png',import.meta.url).href,
    layer13: new URL('./layer13-tries.png', import.meta.url).href,
    layer14: new URL('./layer14-school.png', import.meta.url).href,
    layer15: new URL('./layer15-trees.png', import.meta.url).href,
    layer16: new URL('./layer16-forest_front.png', import.meta.url).href,
    layer17: new URL('./layer17-bridge_front.png', import.meta.url).href,
    layer18: new URL('./layer18-blockers0.png',import.meta.url).href,
    layer19: new URL('./layer19-blockers1.png',import.meta.url).href,
    mapLinks: new URL('./mapLinks.svg',import.meta.url).href,
    trainimg: new URL('./traingamesnip.PNG', import.meta.url).href,
    quiz: new URL('./comic-quiz.jpg', import.meta.url).href,
    learning: new URL('./learning.jpg', import.meta.url).href,
    linkedList: new URL('./linked-list.png', import.meta.url).href,
    nodeman: new URL('./nodeman.svg', import.meta.url).href,
    doublyLinkedList: new URL('./doubly-linked-list.png', import.meta.url).href
};

export default IMAGES